
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1445/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.167.4-microsoft-standard-WSL2 - x86_64
...
